[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_22", "nginx"]
nixLibs = ["libmysqlclient"]

[phases.install]
cmds = [
    "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
    "composer install --ignore-platform-reqs",
    "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf"